services:
  node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101503.1
    ports:
      - 8545:8545
      - 8551:8551
    volumes:
      - ./geth-data:/data
      - ./secret:/secret
    env_file: "test-configs/worldchain-mainnet-stress.env"
    # build: ./reth
    # ports:
    #   - 8545:8545
    #   - 8551:8551
    # volumes:
    #   - ./reth-data:/data
    #   - ./secret:/secret
    # env_file: "test-configs/base-mainnet-replay-reth.env"
  replayor:
    build: .
    command: ["/app/bin/replayor"]
    network_mode: "host"
    env_file: "test-configs/worldchain-mainnet-stress.env"
    volumes:
      - ./secret:/secret
      - ./results:/results
      - ./config:/config
